#include <iostream>

using namespace std;

/**
 * Steps:
 * 
 * Convert the text file to a .o file using objcopy:
 *
 * objcopy --input binary --output-target=elf64-littleaarch64 --binary-architecture aarch64 ../www/index.html index.html.o
 *
 * Validate the symbols:
 * 
 * nm index.html.o
 *
 * Explicitly link the .o into the binary
 *
 * Declare the symbols extern. 
 */

extern "C" {
// Declare the symbols generated by objcopy. Note that the directory name
// appears in the symbol name.
extern const unsigned char _binary____www_index_html_start[];
extern const unsigned char _binary____www_index_html_end[];
// This appears to be zero.
extern const unsigned int _binary____www_index_html_size;
}

int main(int, const char**) {
    // Shows 0?
    cout << _binary____www_index_html_size << endl;
    // Matches the size of the original .html file exactly
    cout << _binary____www_index_html_end - _binary____www_index_html_start << endl;
    cout << (char)_binary____www_index_html_start[0] << endl;
    cout << (char)_binary____www_index_html_start[1] << endl;
}
